### ISSUE TITLE
[Crash] Can't load native library on Android 6.0

### ISSUE THREAD

**Issue by hoangnam9194** [bees4honey/mobile_vin_scanner#22]
App run alright on devices android < 6.0 for android but app crash on device android 6.0

File B4Hscanner.java at following snippet code:
     static {
            System.loadLibrary("b4hvinscanner");
       }

Please recheck it. Thanks.

This is log:
FATAL EXCEPTION: main
                                                                           Process: com.bees4honey.vinscanner, PID: 25452
                                                                           java.lang.UnsatisfiedLinkError: dlopen failed: cannot locate symbol "__aeabi_memclr4" referenced by "/data/app/com.bees4honey.vinscanner-1/lib/arm/libb4hvinscanner.so"...
                                                                               at java.lang.Runtime.loadLibrary(Runtime.java:372)
                                                                               at java.lang.System.loadLibrary(System.java:1076)
                                                                               at com.bees4honey.vinscanner.B4HScanner.<clinit>(B4HScanner.java:127)
                                                                               at com.bees4honey.vinscanner.ScannerFragment$ScannerHandler.<init>(ScannerFragment.java:312)
                                                                               at com.bees4honey.vinscanner.ScannerFragment.<init>(ScannerFragment.java:91)
                                                                               at com.bees4honey.vinscanner.ScannerActivity.instantiateScannerFragment(ScannerActivity.java:151)
                                                                               at com.bees4honey.vinscanner.ScannerActivity.onCreate(ScannerActivity.java:83)
                                                                               at android.app.Activity.performCreate(Activity.java:6303)
                                                                               at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1108)
                                                                               at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2376)
                                                                               at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2483)
                                                                               at android.app.ActivityThread.access$900(ActivityThread.java:153)
                                                                               at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1349)
                                                                               at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                               at android.os.Looper.loop(Looper.java:148)
                                                                               at android.app.ActivityThread.main(ActivityThread.java:5438)
                                                                               at java.lang.reflect.Method.invoke(Native Method)
                                                                               at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:739)
                                                                               at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:629)

**Comment by badmark** [comment]
Are you trying to run the plug in on an arm64 or x86 device; something other than an arm based Android?

**Comment by vantoan8x** [comment]
@badmark, has currently version not work on Android 6+ and device specification based on ARM x86 and ARM64 CPU?

**Comment by badmark** [comment]
@vantoan8x not the developer of this project but that error could either be using the wrong architecture or perhaps not including the proper SDK version.

**Comment by vantoan8x** [comment]
@bees4honey could you help to test on ARM 64 device!

I run on: http://www.gsmarena.com/xiaomi_mi_4-6518.php
SDK not working and give crash as above @hoangnam9194 post.

**Comment by badmark** [comment]
Again, I am not the developer, just trying to help you find your way. You need to have the proper SDK version installed I believe for this plugin is 23, due to permission issues for the camera; also it depends on what version of Android your device is own.

The Snapdragon 801which powers the device you mentioned is not ARM64.

You should take some time to read a bit more about Android versions and their corresponding SDKs. 

https://developer.android.com/guide/topics/manifest/uses-sdk-element.html

That said, I do not believe this is an issue with VIN Scanner but rather your implementation, or lack of SDK libraries that the plug-in expects.

**Comment by nik123** [comment]
Working on it. The arm64 devices should work fine. The issue seems to affect only non 64-bit arm devices with Android 6 or higher. As @badmark has mentioned before xiaomi mi 4 is not ARM64 device.

**Comment by vantoan8x** [comment]
as the log above, as my know it said: __aeabi_memclr4
that mean the function memclr(4 params) in architecture aeabi was not exited!

@bees4honey  could you help and check this?

**Comment by vantoan8x** [comment]
Other way, I run demo app form VIN SDK, it also crashed and give same log bug.

**Comment by nik123** [comment]
Does previous version also crashes on the same devices?

**Comment by badmark** [comment]
What do you have set for compileSdkVersion and targetSdkVersion?

Can you try setting them to this: (compileSdkVersion=24, targetSdkVersion=23)?

This thread I think covers this issue well: https://github.com/android-ndk/ndk/issues/126

**Comment by hoangnam9194** [comment]
Thank for your help @badmark 
I tried with (compileSdkVersion=24, targetSdkVersion=23) but it also crashed and give same above log.
