### ISSUE TITLE
Fatal error using scanner plugin with cordova android 6.x

### ISSUE THREAD

**Issue by gtczap** [bees4honey/mobile_vin_scanner#26]
I am getting this fatal exception when I run the cordova plugin vin code scanner on android.

Cordova Android platform version: 6.1.2 (latest)
Android Target SDK: 25 (default)
Device Android version: 6.0.1 (latest)
Scanner version: Master Branch @ 3/17/17 (latest)

```
03-17 15:01:47.716: E/AndroidRuntime(3679): FATAL EXCEPTION: main
03-17 15:01:47.716: E/AndroidRuntime(3679): Process: com.myapp, PID: 3679
03-17 15:01:47.716: E/AndroidRuntime(3679): java.lang.UnsatisfiedLinkError: dlopen failed: cannot locate symbol "__aeabi_memclr4" referenced by "/data/app/com.myapp-2/lib/arm/libb4hvinscanner.so"...
03-17 15:01:47.716: E/AndroidRuntime(3679): 	at java.lang.Runtime.loadLibrary(Runtime.java:372)
03-17 15:01:47.716: E/AndroidRuntime(3679): 	at java.lang.System.loadLibrary(System.java:1076)
03-17 15:01:47.716: E/AndroidRuntime(3679): 	at com.bees4honey.vinscanner.B4HScanner.<clinit>(B4HScanner.java:127)
03-17 15:01:47.716: E/AndroidRuntime(3679): 	at com.bees4honey.vinscanner.ScannerFragment$ScannerHandler.<init>(ScannerFragment.java:312)
03-17 15:01:47.716: E/AndroidRuntime(3679): 	at com.bees4honey.vinscanner.ScannerFragment.<init>(ScannerFragment.java:91)
03-17 15:01:47.716: E/AndroidRuntime(3679): 	at com.bees4honey.vinscanner.ScannerActivity.instantiateScannerFragment(ScannerActivity.java:151)
03-17 15:01:47.716: E/AndroidRuntime(3679): 	at com.bees4honey.vinscanner.ScannerActivity.onCreate(ScannerActivity.java:83)
03-17 15:01:47.716: E/AndroidRuntime(3679): 	at android.app.Activity.performCreate(Activity.java:6259)
03-17 15:01:47.716: E/AndroidRuntime(3679): 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1130)
03-17 15:01:47.716: E/AndroidRuntime(3679): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2379)
03-17 15:01:47.716: E/AndroidRuntime(3679): 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2490)
03-17 15:01:47.716: E/AndroidRuntime(3679): 	at android.app.ActivityThread.access$900(ActivityThread.java:154)
03-17 15:01:47.716: E/AndroidRuntime(3679): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1354)
03-17 15:01:47.716: E/AndroidRuntime(3679): 	at android.os.Handler.dispatchMessage(Handler.java:102)
03-17 15:01:47.716: E/AndroidRuntime(3679): 	at android.os.Looper.loop(Looper.java:148)
03-17 15:01:47.716: E/AndroidRuntime(3679): 	at android.app.ActivityThread.main(ActivityThread.java:5443)
03-17 15:01:47.716: E/AndroidRuntime(3679): 	at java.lang.reflect.Method.invoke(Native Method)
03-17 15:01:47.716: E/AndroidRuntime(3679): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:728)
03-17 15:01:47.716: E/AndroidRuntime(3679): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:618)
```

**Comment by gtczap** [comment]
Reverting to a previous revision averts this error: https://github.com/bees4honey/mobile_vin_scanner#06533e95c03a5e940ba3c147808bdeb46761484d:/phonegap_vin_scanner_plugin

**Comment by middletonsp** [comment]
I'm getting the exact same error. I tried reverting to the proper commit version that you used, but it did not fix it. Did you just revert all your files to that commit or did you revert the sdk? Any additional information would be helpful, thanks!

**Comment by nik123** [comment]
> Did you just revert all your files to that commit or did you revert the sdk? 

The bug is caused only by *.so files itself, so reverting them should be enough. 

Do you experiencing problems with any 6.x devices or specific ones?
